a = Analysis(
    ['scraper.py'],
    pathex=['..'],
    binaries=[],
    datas=[
        ('../shared/models.py', '.'),
    ],
    hiddenimports=[
        'playwright',
        'playwright.sync_api',
        'aiohttp',
        'aiofiles',
        'requests',
        'shared.models',
        'shared.progress_state',
        'shared.config_schema',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='scraper_worker',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)